# Generated by Django 5.2.1 on 2025-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Network Node",
                "verbose_name_plural": "Network Nodes",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product",
                     "verbose_name_plural": "Products"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="network_node",
        ),
        migrations.AddField(
            model_name="product",
            name="nodes",
            field=models.ManyToManyField(
                related_name="products", to="network.networknode"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2,
                                      default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(decimal_places=2,
                                      default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(fields=["city"],
                               name="network_net_city_874107_idx"),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["country"], name="network_net_country_4e9322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"],
                               name="network_pro_name_d7debe_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["model"],
                               name="network_pro_model_0e6401_idx"),
        ),
    ]
